"""empty message

Revision ID: 3005286c4998
Revises: e4bb2ed34b65
Create Date: 2018-09-26 01:24:57.266398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3005286c4998'
down_revision = 'e4bb2ed34b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts_docker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('type_device_id', sa.String(length=80), nullable=True),
    sa.Column('bridge_docker', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hosts_docker')
    # ### end Alembic commands ###
