"""empty message

Revision ID: bdefd8018223
Revises: 9092c069465a
Create Date: 2018-10-21 19:24:07.686064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdefd8018223'
down_revision = '9092c069465a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_dpid', sa.String(length=50), nullable=True),
    sa.Column('rx', sa.Integer(), nullable=True),
    sa.Column('tx', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    # ### end Alembic commands ###
