"""empty message

Revision ID: c2e89543c6ff
Revises: bdefd8018223
Create Date: 2018-10-21 20:32:31.046183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e89543c6ff'
down_revision = 'bdefd8018223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('last_rx', sa.Integer(), nullable=True))
    op.add_column('stats', sa.Column('last_tx', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats', 'last_tx')
    op.drop_column('stats', 'last_rx')
    # ### end Alembic commands ###
